apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: labip
  labels: 
    app: nginx 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec: 
      containers: 
      - name: nginx 
        image: "ifilyaninitmo/itdt-contained-frontend:master"
        env: 
        - name: REACT_APP_USERNAME 
          value: "hello would" 
        - name: REACT_APP_COMPANY_NAME 
          value: "goodbye would" 
        ports: 
        - containerPort: 3000